import puppeteer from "puppeteer";
import { readFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { marked } from "marked";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LOGO_DATA_URI = (() => {
  const logoPath = path.resolve(__dirname, "../../../assets/kasagreen.png");
  const buffer = readFileSync(logoPath);
  return `data:image/png;base64,${buffer.toString("base64")}`;
})();

export async function generatePDF(
  assessmentMarkdown: string,
): Promise<Buffer> {
  const logoUri = LOGO_DATA_URI;
  const rawHtml = marked(assessmentMarkdown) as string;
  const htmlContent = rawHtml
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<iframe[\s\S]*?<\/iframe>/gi, "")
    .replace(/<object[\s\S]*?<\/object>/gi, "")
    .replace(/<embed[\s\S]*?>/gi, "")
    .replace(/\son\w+\s*=\s*["'][^"']*["']/gi, "");

  const html = `<!DOCTYPE html>
    <html><head><meta charset="utf-8">
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; line-height: 1.5; padding: 40px; color: #1f2937; }
      h1 { font-size: 22px; color: #065f46; }
      h2 { font-size: 18px; color: #065f46; margin-top: 24px; }
      h3 { font-size: 15px; margin-top: 16px; }
      p { margin: 8px 0; }
      ul, ol { margin: 8px 0 8px 20px; }
    </style></head>
    <body>
      ${htmlContent}
    </body></html>`;

  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const page = await browser.newPage();
    await page.setJavaScriptEnabled(false);
    await page.setRequestInterception(true);
    page.on("request", (req) => {
      if (req.url().startsWith("data:")) req.continue();
      else req.abort();
    });
    await page.setContent(html, { waitUntil: "domcontentloaded" });

    const pdf = await page.pdf({
      format: "letter",
      margin: { top: "0.5in", right: "0.5in", bottom: "0.75in", left: "0.5in" },
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: "<div></div>",
      footerTemplate: `
        <div style="display:flex; width:100%; justify-content:center; align-items:center; font-size:10px; padding:0 0.5in; opacity:0.7;">
          <span>Generated by</span>
          <img src="${logoUri}" style="height:16px; margin:0 4px;" />
          <span>Boafo • ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
        </div>`,
    });

    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
