import puppeteer from "puppeteer";
import { readFileSync } from "fs";
import path from "path";
import { marked } from "marked";

function getLogoDataUri(): string {
  const logoPath = path.resolve(__dirname, "../../../assets/kasagreen.png");
  const buffer = readFileSync(logoPath);
  return `data:image/png;base64,${buffer.toString("base64")}`;
}

export async function generatePDF(
  assessmentMarkdown: string,
  sources?: string[]
): Promise<string> {
  const logoUri = getLogoDataUri();
  const htmlContent = marked(assessmentMarkdown);

  const html = `<!DOCTYPE html>
    <html><head><meta charset="utf-8">
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; line-height: 1.5; padding: 40px; color: #1f2937; }
      h1 { font-size: 22px; color: #065f46; }
      h2 { font-size: 18px; color: #065f46; margin-top: 24px; }
      h3 { font-size: 15px; margin-top: 16px; }
      p { margin: 8px 0; }
      ul, ol { margin: 8px 0 8px 20px; }
      .sources { margin-top: 30px; border-top: 1px solid #d1d5db; padding-top: 16px; }
      .source { font-size: 12px; color: #6b7280; margin: 4px 0; }
    </style></head>
    <body>
      ${htmlContent}
      ${sources?.length ? `<div class="sources"><h3>References</h3>${sources.map((s, i) => `<div class="source">${i + 1}. ${s}</div>`).join("")}</div>` : ""}
    </body></html>`;

  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: "networkidle0" });

  const pdf = await page.pdf({
    format: "letter",
    margin: { top: "0.5in", right: "0.5in", bottom: "0.75in", left: "0.5in" },
    printBackground: true,
    displayHeaderFooter: true,
    headerTemplate: "<div></div>",
    footerTemplate: `
      <div style="display:flex; width:100%; justify-content:center; align-items:center; font-size:10px; padding:0 0.5in; opacity:0.7;">
        <span>Generated by</span>
        <img src="${logoUri}" style="height:16px; margin:0 4px;" />
        <span>Boafo • ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
      </div>`,
  });

  await browser.close();
  return Buffer.from(pdf).toString("base64");
}
