# Documentation Schema
# This schema MUST be validated before writing any documentation file

required_fields:
  module:
    type: string
    description: "Module/area of the project"
    examples:
      - "Authentication"
      - "Game Engine"
      - "Rendering"

  date:
    type: string
    pattern: '^\d{4}-\d{2}-\d{2}$'
    description: "Date when this problem was solved (YYYY-MM-DD)"

  problem_type:
    type: enum
    values:
      - build_error          # Compilation, bundle errors
      - test_failure         # Test failures, flaky tests
      - runtime_error        # Exceptions, crashes during execution
      - performance_issue    # Slow queries, memory issues
      - database_issue       # Migration, query, schema problems
      - security_issue       # Authentication, authorization, XSS
      - ui_bug               # Frontend, rendering issues
      - integration_issue    # External service, API integration problems
      - logic_error          # Business logic bugs
      - developer_experience # DX issues: workflow, tooling, dev setup
      - workflow_issue       # Development process, missing steps
      - best_practice        # Documenting patterns and practices to follow
      - documentation_gap    # Missing or inadequate documentation
    description: "Primary category of the problem"

  component:
    type: string
    description: "Technical component involved (project-specific)"

  symptoms:
    type: array[string]
    min_items: 1
    max_items: 5
    description: "Observable symptoms (error messages, visual issues, crashes)"

  root_cause:
    type: string
    description: "Fundamental cause of the problem"

  resolution_type:
    type: enum
    values:
      - code_fix             # Fixed by changing source code
      - migration            # Fixed by database migration
      - config_change        # Fixed by changing configuration
      - test_fix             # Fixed by correcting tests
      - dependency_update    # Fixed by updating dependency
      - environment_setup    # Fixed by environment configuration
      - workflow_improvement # Improved development workflow
      - documentation_update # Added or updated documentation
      - tooling_addition     # Added helper script or automation
    description: "Type of fix applied"

  severity:
    type: enum
    values:
      - critical             # Blocks production or development
      - high                 # Impairs core functionality
      - medium               # Affects specific feature
      - low                  # Minor issue or edge case
    description: "Impact severity"

optional_fields:
  tags:
    type: array[string]
    max_items: 8
    description: "Searchable keywords (lowercase, hyphen-separated)"

validation_rules:
  - "date must be in YYYY-MM-DD format"
  - "problem_type must match one of the enum values"
  - "symptoms must be specific and observable (not vague)"
  - "severity must match one of the enum values"
  - "tags should be lowercase, hyphen-separated"
